[cosmic-ray]
module-path = "app"
test-command = "python -m pytest -q"
timeout = 20

[cosmic-ray.distributor]
name = "local"

[cosmic-ray.mutants]
operators = [
    "core/ReplaceBinaryOperator",
    "core/ReplaceComparisonOperator",
    "core/ReplaceArithmeticOperator"
]
